// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

using SampleApi.Infrastructure.Data;

#nullable disable

namespace SampleApi.Migrations
{
  [DbContext(typeof(ApplicationDbContext))]
  [Migration("20251028141954_fix_naming_convention")]
  partial class fix_naming_convention
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "9.0.10")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("SampleApi.Models.Employee", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer")
                      .HasColumnName("id");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<string>("Name")
                      .IsRequired()
                      .HasColumnType("text")
                      .HasColumnName("name");

            b.Property<string>("Position")
                      .IsRequired()
                      .HasColumnType("text")
                      .HasColumnName("position");

            b.Property<decimal>("Salary")
                      .HasColumnType("numeric")
                      .HasColumnName("salary");

            b.HasKey("Id")
                      .HasName("pk_employees");

            b.ToTable("employees");
          });

      modelBuilder.Entity("SampleApi.Models.User", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<DateTime>("CreatedAt")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("Email")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<string>("PasswordHash")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<string>("Role")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<string>("Username")
                      .IsRequired()
                      .HasColumnType("text");

            b.HasKey("Id")
                      .HasName("pk_users");

            b.ToTable("users");
          });
#pragma warning restore 612, 618
    }
  }
}
